DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS UserProfileSettings;
DROP TABLE IF EXISTS UserType;
DROP TABLE IF EXISTS Neighborhood;
DROP TABLE IF EXISTS Incident;
DROP TABLE IF EXISTS Thread;
DROP TABLE IF EXISTS ThreadResponse;
DROP TABLE IF EXISTS ThreadFeedback;
DROP TABLE IF EXISTS Pest;

